# Site
name: "Dechen Chuteng Designs | @by.dpc"
title: "Dechen Chuteng Designs | @by.dpc"
description: "Hi, welcome to my design portfolio! üå± ‚ö°Ô∏è"
logo: "assets/images/apple-touch-icon.png"
favicon: "assets/images/apple-touch-icon.png"
baseurl: ""
google_analytics: "UA-165009249-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
email: dechxpal@gmail.com

# Authors
authors:
  dc:
    name: Dechen Chuteng
    display_name: Dechen
    gravatar: d5798961deded2b3f3e66e181ad65085
    email: dechxpal@gmail.com
    web: https://www.dechenc.com
    twitter: https://twitter.com/ddsooxo
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
